apiVersion: apps/v1
kind: Deployment
metadata:
 name: hello-world-deployment
 namespace: app
 labels:
  app: hello-world
spec:
 replicas: 3
 selector:
  matchLabels:
   app: hello-world
 template:
  metadata:
   labels:
    app: hello-world
  spec:
   containers:
    - name: hello-world
      image: saralinnea83/hello-world:latest
      imagePullPolicy: IfNotPresent